name: CI Makefile

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'

jobs:
  perl-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          #- '5.30'
          #- '5.32'
          - 'latest'
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - name: Print out VM timezone information
        run: |
            timedatectl

      - uses: actions/checkout@v2
      - name: Regular tests
        run: |
            prove -lv t/0*.t
